// playground/solid-app/TestComponent.tsx
import { Component } from 'solid-js'

const TestComponent: Component = () => {
  return (
    <div style={{ 'background-color': 'green', padding: '20px', 'margin-top': '10px' }}>
      <h1 style={{ 'font-size': '24px', color: 'white', 'text-align': 'center' }}>
        Solid Test Component
      </h1>
      <p style={{ 'font-size': '16px', 'line-height': '1.5', 'margin-bottom': '15px' }}>
        This is a test component with inline styles for Solid.
        Select the component and run "Extract Inline Styles to CSS Module" command.
      </p>
      <button style={{ 'background-color': 'white', color: 'green', padding: '10px 20px', 'border-radius': '4px', border: 'none' }}>
        Click Me
      </button>
    </div>
  )
}

export default TestComponent

// playground/solid-app/src/TestComponent.tsx
import styles from './TestComponent.module.css'

function Comp(props: {style: Record<string, any>}){
  return <></>
}

export default () => {
  return (
    <div style={{ 'background-color': 'white', color: 'blue', padding: '10px 20px', 'border-radius': '4px', border: 'none' }}>
      <Comp style={{ 'background-color': 'white', color: 'blue', padding: '10px 20px', 'border-radius': '4px', border: 'none' }}/>
      <h1 style={{ 'background-color': 'white', color: 'blue', padding: '10px 20px', 'border-radius': '4px', border: 'none' }}>
        React Test Component
      </h1>
      <p style={{ 'background-color': 'white', color: 'blue', padding: '10px 20px', 'border-radius': '4px', border: 'none' }}>
        This is a test component with inline styles for React.
        Select the component and run "Extract Inline Styles to CSS Module" command.
      </p>
      <button style={{ 'background-color': 'white', color: 'blue', padding: '10px 20px', 'border-radius': '4px', border: 'none' }}>
        Click Me
      </button>
    </div>
  )
}
